version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '8080:80'
    depends_on:
      - app
      - mysqldb
    networks:
      - node-network

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    entrypoint: dockerize -wait tcp://mysqldb:3306 -timeout 20s sh -c "npm install && npm run start"
    tty: true
    depends_on:
      - mysqldb
    ports:
      - "3000:3000"

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
   driver: bridge